name: Build and publish

# on:
#   push:
#     branches: [main]

on: [push]

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            target: windows
          - os: ubuntu-latest
            arch: amd64
            target: linux
          - os: macos-latest
            arch: amd64
            target: darwin
          - os: macos-latest
            arch: arm64
            target: darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.2"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build binary and prepare archive for publish
        shell: bash
        run: |
          ./install.sh
          export GOOS=${{ matrix.target }}
          export GOARCH=${{ matrix.arch }}
          ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Playground-plugin-${{ matrix.target }}_${{ matrix.arch }}
          path: build
