name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build binary and prepare archive for publish
        shell: bash
        run: |
          ./install.sh
          ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Playground-plugin-${{ matrix.os }}
          path: build